// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf45u9mHKgh9AgVvubzQAEO2cyB0cYT28',
    appId: '1:951099900733:web:a3330292e1af33a4a8bb54',
    messagingSenderId: '951099900733',
    projectId: 'demofirebase-f428c',
    authDomain: 'demofirebase-f428c.firebaseapp.com',
    storageBucket: 'demofirebase-f428c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkJ08Yyw4lXUY4_VQ0c5EbrLs6DFRMl2U',
    appId: '1:951099900733:android:180e44ca6be5d16da8bb54',
    messagingSenderId: '951099900733',
    projectId: 'demofirebase-f428c',
    storageBucket: 'demofirebase-f428c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_7p5Wc2XSkdEJJMzuz3pHrRKeKmAz_uU',
    appId: '1:951099900733:ios:e6e8c227c23f6f4fa8bb54',
    messagingSenderId: '951099900733',
    projectId: 'demofirebase-f428c',
    storageBucket: 'demofirebase-f428c.appspot.com',
    iosClientId: '951099900733-p98hhj4a53btpcloa3okluukui7lc9sq.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_7p5Wc2XSkdEJJMzuz3pHrRKeKmAz_uU',
    appId: '1:951099900733:ios:e6e8c227c23f6f4fa8bb54',
    messagingSenderId: '951099900733',
    projectId: 'demofirebase-f428c',
    storageBucket: 'demofirebase-f428c.appspot.com',
    iosClientId: '951099900733-p98hhj4a53btpcloa3okluukui7lc9sq.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBf45u9mHKgh9AgVvubzQAEO2cyB0cYT28',
    appId: '1:951099900733:web:7e2e75447dc51e74a8bb54',
    messagingSenderId: '951099900733',
    projectId: 'demofirebase-f428c',
    authDomain: 'demofirebase-f428c.firebaseapp.com',
    storageBucket: 'demofirebase-f428c.appspot.com',
  );

}